### ISSUE TITLE
Doc: edit `parallel` cookbook to use the one-liner

### ISSUE THREAD

**Issue by abey79** [abey79/vpype#108]
see https://github.com/abey79/vpype/issues/5#issuecomment-737268789

```bash
parallel --plus vpype read {} linemerge linesort write {/.svg/_processed.svg} ::: *.svg
```

**Comment by tatarize** [comment]
But, what if I wanted to sort my svg documents based on the length of their paths? Or take 20 embroidery files I have laying around and export them into a grid of a single svg? Or what if I'm really just a windows user and don't have access to commands like parallel.

**Comment by abey79** [comment]
> But, what if I wanted to sort my svg documents based on the length of their paths?

```
parallel "echo -n '{} '; vpype read {} stat | grep Length | tail -n 1 | sed 's/.* //'" ::: *.svg | sort -k 2
```

> Or take 20 embroidery files I have laying around and export them into a grid of a single svg?

I can't think of an immediately available easy way for this. You'd have to have a script that builds a pipeline similar to:
```vpype read file1.svg translate 10cm 0 read file2.svg translate 10cm 0 ...```. That could be a nice little script to add in the examples.

> Or what if I'm really just a windows user and don't have access to commands like parallel.

That makes me sad. Not sure such a lost cause is redeemable. /s

**Comment by tatarize** [comment]
> `parallel "echo -n '{} '; vpype read {} stat | grep Length | tail -n 1 | sed 's/.* //'" ::: *.svg | sort -k 2`

It just rolls right off the tongue. Swiss army knife, +6 linux tools.

* "I want to do this one somewhat complex thing with vectors."
     * "Oh, you can do that in one line with this one cool project called vpype, `pip install vpype` now install a new os for these other 6 tools..."
