### ISSUE TITLE
WARNING:root:!!! `vpype.Length` is deprecated, use `vpype.LengthType` instead.

### ISSUE THREAD

**Issue by vmario89** [abey79/vpype#240]
Hi,
running with Python 3.8.5 and latest commit i get the following warning for all executions:

```WARNING:root:!!! `vpype.Length` is deprecated, use `vpype.LengthType` instead.```

**Comment by abey79** [comment]
Hello @vmario89, this appears to be a duplicated of #228, which I haven't been able to reproduce so far. Do you confirm that you observe this behaviour in a new virtual environment, in particular devoid of any (possibly outdated) plug-in?

**Comment by vmario89** [comment]
hey,. thanks for that link. i did it exactly the same with ubuntu 20 lts and latest vpype installed using pip3.

i tried to silence the module but no luck at all using logging disabler. it still wants to tell me that warning
https://stackoverflow.com/questions/27538879/how-to-disable-loggers-from-other-modules

**Comment by abey79** [comment]
I'm closing this as it is likely not an issue related to vpype itself (rather a plug-in). Please do reopen if you still have the issue with vpype only.
