### ISSUE TITLE
Fix crash with Click 8.0

### ISSUE THREAD

**Issue by vmario89** [abey79/vpype#273]
Hi,
i updated some of my pip modules. Now i get the following warnings:

```
/home/tomate/.local/lib/python3.8/site-packages/vpype_cli/cli.py:126: DeprecationWarning: 'resultcallback' has been renamed to 'result_callback'. The old name will be removed in Click 8.1.
  @cli.resultcallback()
/home/tomate/.local/lib/python3.8/site-packages/vpype_cli/cli.py:108: DeprecationWarning: 'get_os_args' is deprecated and will be removed in Click 8.1. Access 'sys.argv[1:]' directly instead.
  cmd_string = "vpype " + " ".join(shlex.quote(arg) for arg in get_os_args()) + "\n"
Error in vpype:'int' object has no attribute 'lower'
```

**Comment by abey79** [comment]
Thanks for reporting. Indeed, Click has released a new major version and there might be some change I need to do for compatibility.

**Comment by abey79** [comment]
I can't directly reproduce this error, can you provide the full command which triggers it?

**Comment by vmario89** [comment]
Hi. They are thrown when running https://gitea.fablabchemnitz.de/MarioVoigt/mightyscape-1.X/src/branch/master/extensions/fablabchemnitz/vpypetools/vpypetools.py from an inkscape extension call, like linesort

![grafik](https://user-images.githubusercontent.com/5631071/118671007-6721b700-b7f7-11eb-9f6a-39a1b26fbf31.png)

**Comment by abey79** [comment]
I can reproduce now, and I see that it's actually a crash in addition to deprecation warnings. Working on it.

**Comment by abey79** [comment]
The workaround it to use a pre-8 version of Click.
