### ISSUE TITLE
Bug: linesimplify skips for layers with a single path

### ISSUE THREAD

**Issue by abey79** [abey79/vpype#280]
...due to a stupid check likely copy/pasted from linemerge/linesort

<img width="206" alt="image" src="https://user-images.githubusercontent.com/49431240/120008244-0d7d7180-bfdb-11eb-9570-4feb4f19927d.png">

**Comment by Ohmarinus** [comment]
For a quick fix you can set 
```173 if len(lines) < 1:
174        return lines```
in the `operations.py` file in the `vpype_cli` folder.
