### ISSUE TITLE
Trying to work with fills

### ISSUE THREAD

**Issue by ricdp** [abey79/vpype#303]
Hi, I am using this wonderful tool to clean svg and generate gcode for a pen plotter but I haven't been able to transform fills into gcode, it shows just the stroke. 

The basic example  `vpype read test1.svg write test2.svg`, where test1 has only one circle with fill and no stroke generates a circle with stroke and no fill.

Am I missing something?

**Comment by abey79** [comment]
Hello @ricdp, vpype does not automatically generate fills. There are a couple of commands available through plug-ins which implement fills:
- my own `fill` command in https://github.com/abey79/vpype-explorations
- the `efill` command in https://github.com/EmbroidePy/vpype-embroidery

**Comment by ricdp** [comment]
Ok, thank you very much!
