### ISSUE TITLE
linesimplify should filter out tiny segments

### ISSUE THREAD

**Issue by abey79** [abey79/vpype#40]
Tiny segments (start/end point closer to some small threshold) are often generated by 3D to 2D renderers. They increase plotting time and maybe detrimental to plot quality. `linesimplify` should filter them out.

**Comment by ithinkido** [comment]
A quick test piece cut out of a real example, the line is hidden in the green circle.

[mini_line_test.zip](https://github.com/abey79/vpype/files/4870501/mini_line_test.zip)

**Comment by abey79** [comment]
Finally, this will be implemented as a separate `filter` command: #76
