### ISSUE TITLE
New Feature: Add DM/PL as output format

### ISSUE THREAD

**Issue by OzHawk** [abey79/vpype#522]
The current implementation of vpype only allows SVG or HPGL output.  To support Houston Instrument plotters that do not have HPGL compatibility mode, DM/PL format output should be added as an option for 'write' functionality.
The document "DM/PL Command Language", Houston Instruments, Copyright 1984, describes the complete language command structure/protocol.

**Comment by abey79** [comment]
Please try to implement this as a [vpype-gcode](https://github.com/plottertools/vpype-gcode) profile. In the future, I don't plan on "hard-coding" new output format in vpype. Instead, the plan is to integrate vpype-gcode and its profiles.

**Comment by abey79** [comment]
What do you mean by "device configuration"? With vpype-gcode, you can simply create a profile in a ~/.vpype.toml config file.

**Comment by abey79** [comment]
As for your question on developing on vpype, the best is to fork on GitHub, checkout on your computer, make a branch and commit to your fork, and the create a pull request.

**Comment by OzHawk** [comment]
One of the significant differences between GCode and HPGL and DM/PL is the units.  GCode uses real world units, where as HPGL and DM/PL use plotter units which map to real world units via a step size.  How do you envisage this difference being implemented within `vpype-gcode`?
Thanks

**Comment by abey79** [comment]
You can make any number of vpype-profiles too, so you can cover multiple devices if needed.

vpype-gcode lets you specify which units you want to work with, as well as offsets and axes orientation (see [this section](https://github.com/plottertools/vpype-gcode#output-control) of the readme).

**Comment by ithinkido** [comment]
> One of the significant differences between GCode and HPGL and DM/PL is the units. GCode uses real world units, where as HPGL and DM/PL use plotter units which map to real world units via a step size. How do you envisage this difference being implemented within `vpype-gcode`? Thanks

[These profiles](https://github.com/plottertools/vpype-gcode/blob/35468e3beee15fb9a0919f18a81a19c7931ff102/vpype_gcode/bundled_configs.toml#L59-L106) were made for HPGL as well as  non HPGL plotters. using vpype-gcode    

You can use these as a base to understand what you need. They cover both non standard commands and non standard units.

**Comment by abey79** [comment]
Closing this as it is addressed by vpype-gcode.
