### ISSUE TITLE
Bug: implicit simplify in `read` hangs with some file

### ISSUE THREAD

**Issue by abey79** [abey79/vpype#53]
The attached file will have `read` hang unless `--no-simplify` is used. Weirdly, a subsequent `linesimplify` works without issue.

[bar.svg.zip](https://github.com/abey79/vpype/files/5116985/bar.svg.zip)

**Comment by carewdavid** [comment]
It looks like the `read` does complete after an extremely long time.

```
$ time vpype read bar.svg write foo.svg

real    45m2.342s
user    44m46.110s
sys     0m2.441s
```

**Comment by abey79** [comment]
I still haven't looked in details at this, but now I wonder if it's not another instance of this issue pygeos/pygeos#195.
