### ISSUE TITLE
Can't install on macOS

### ISSUE THREAD

**Issue by deranku** [abey79/vpype#602]
Hi,
using Big Sur 11.7.4 with Python 3.11.2. Pipx installed without error via Homebrew. But installing vpype as suggested in the readme.md fails. I've attached the logs. What could be causing the error?
thank you, 
Philip

```
➜  ~ pipx install "vpype[all]"
Fatal error from pip prevented installation. Full pip output in file:
    /Users/rakete/.local/pipx/logs/cmd_2023-03-08_13.33.35_pip_errors.log

pip seemed to fail to build package:
    vpype[all]

Some possibly relevant errors from pip install:
    ERROR: Cannot install vpype[all]==1.4.0, vpype[all]==1.5.0, vpype[all]==1.5.1, vpype[all]==1.6.0, vpype[all]==1.7.0, vpype[all]==1.8.0, vpype[all]==1.8.1 and vpype[all]==1.9.0 because these package versions have conflicting dependencies.
    ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Error installing vpype from spec 'vpype[all]'.
```

Logs:
[cmd_2023-03-08_13.33.35_pip_errors.txt](https://github.com/abey79/vpype/files/10920682/cmd_2023-03-08_13.33.35_pip_errors.txt)
[cmd_2023-03-08_13.33.35_pip_errors.log](https://github.com/abey79/vpype/files/10920683/cmd_2023-03-08_13.33.35_pip_errors.log)

**Comment by abey79** [comment]
Hi. vpype doesn't currently support Python 3.11. Python 3.10 is recommended. I don't know if you can install it along 3.11 with Homebrew. You may certainly use the official installer from https://python.org. There is no need to uninstall your existing Python 3.11, nor `pipx`. You can then install vpype by specifying the full path to the Python 3.10 interpreter:

```
pipx install 'vpype[all]' --python /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
```

This path is valid for the official installer. I'm not sure what the path would be for a Homebrew-installed Python 3.10.

**Comment by deranku** [comment]
Thanks for the response! Managing Python versions on macOS is a painful experience, but I finally managed to install 3.10 and vpype installed flawlessly.

Sidenote to Mac users facing similar problems: I installed Python 3.10 via Homebrew: `brew install python@3.10`. This way, you can maintain multiple Python versions.
Then, since I have multiple Python versions insalled, I set the 3.10 branch as default as described here: [https://dev.to/malwarebo/how-to-set-python3-as-a-default-python-version-on-mac-4jjf](url).
Now, installing pipx via Homebrew gave me the same error as in the original posting. Uninstalled that and installed via pip led to success. So, basically as described in the docs 8-) [https://vpype.readthedocs.io/en/latest/install.html](url)
